services:
  - type: web
    name: travel-planner-chatbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn trip_planner_chatbot:app
    pythonVersion: 3.10.13
    region: oregon
    plan: free
