services:
  - type: web
    name: travel-planner-chatbot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn travelmate:app
    envVars:
      - key: PORT
        value: 10000
