services:
  - type: web
    name: travel-planner-chatbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn trip_planner_chatbot:app
    pythonVersion: 3.10.0
    plan: free
    region: oregon

